### ISSUE TITLE
Could this tool parse a part of C code?

### ISSUE THREAD

**Issue by BodyCSoulN** [cedricrupb/code_tokenize#1]
Could this tool parse a part of C code?

For example:
```c
ffp_reset_internal ( ffp )
```

**Comment by cedricrupb** [comment]
code.tokenize (or more precisely the parsing backend based on [tree-sitter](https://tree-sitter.github.io/tree-sitter/))
can parse incomplete source code.

You can actually lookup how tree-sitter would parse your code [here](https://tree-sitter.github.io/tree-sitter/playground).

Tokenization in code.tokenize is reliable in most cases, even with incomplete code. However, the result of an AST parsing on incomplete code can sometimes be surprising.

**Comment by BodyCSoulN** [comment]
Thanks for you help!!
